name: PhoneTag
options:
  bundleIdPrefix: com.phonetag
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    GENERATE_INFOPLIST_FILE: true
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: ""

packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
  swift-dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    from: "1.0.0"

targets:
  PhoneTag:
    type: application
    platform: iOS
    sources:
      - path: PhoneTag
        excludes:
          - "**/.DS_Store"
    resources:
      - path: PhoneTag/Resources/Assets.xcassets
      - path: PhoneTag/Resources/GoogleService-Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.phonetag.app
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "Phone Tag needs your location to show you on the map and enable tagging nearby players."
        INFOPLIST_KEY_NSLocationAlwaysAndWhenInUseUsageDescription: "Phone Tag needs background location access to notify you when tagged and track tripwire crossings during active games."
        INFOPLIST_KEY_UIBackgroundModes: "location remote-notification"
    dependencies:
      - package: firebase-ios-sdk
        product: FirebaseAuth
      - package: firebase-ios-sdk
        product: FirebaseDatabase
      - package: firebase-ios-sdk
        product: FirebaseMessaging
      - package: firebase-ios-sdk
        product: FirebaseAnalytics
      - package: swift-dependencies
        product: Dependencies
